config/routes.rb
Rails.application.routes.draw do
  
  resources :jobs
  resources :staffs do 
    get 'staff_list', on: :collection
  end
  resources :deployment_orders
  resources :rigs
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "deployment_orders#index" 
end

app/models/deployment_order.rb
class DeploymentOrder < ApplicationRecord
	belongs_to :rig
	belongs_to :job
	has_many :unit_deployeds, dependent: :destroy
  accepts_nested_attributes_for :unit_deployeds, allow_destroy: true
  has_many :cement_unit_deployeds, dependent: :destroy
  accepts_nested_attributes_for :cement_unit_deployeds, allow_destroy: true, :reject_if => :reject_cement_unit
  has_many :head_parties, dependent: :destroy
  accepts_nested_attributes_for :head_parties, allow_destroy: true, :reject_if => :reject_party
  has_many :main_parties, dependent: :destroy
  accepts_nested_attributes_for :main_parties, allow_destroy: true, :reject_if => :reject_party
  has_many :light_vehicals, dependent: :destroy
  accepts_nested_attributes_for :light_vehicals, allow_destroy: true, reject_if: :all_blank
  has_many :job_incharges, dependent: :destroy
  accepts_nested_attributes_for :job_incharges, allow_destroy: true, reject_if: :all_blank

  validates :date_of_duty, :well_name, :departure_time, :rig_id, presence: true

  def reject_cement_unit(attributed)
    attributed['vehicle_name'].blank? || attributed['quantity'].blank?
  end

  def reject_party(attributed)
    attributed['staff_id'].blank?
  end
end

app/controllers/deployment_orders_controller.rb
class DeploymentOrdersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_deployment_order, only: [:edit, :show, :update, :destroy]
  before_action :get_rigs, only: [:new, :create, :edit, :show]

  def index
    @deployment_orders = DeploymentOrder.order("date_of_duty DESC").paginate(page: params[:page], per_page: 10)
  end

  def new
    @deployment_order = DeploymentOrder.new
    unit_deployed = @deployment_order.unit_deployeds.build
    unit_deployed.unit_deployed_staffs.build
    cement_unit_deployed = @deployment_order.cement_unit_deployeds.build
    @deployment_order.head_parties.build
    @deployment_order.main_parties.build
    @deployment_order.light_vehicals.build
    @deployment_order.job_incharges.build
    
  end

  def create
    @deployment_order = DeploymentOrder.new(deployment_order_params)
    if @deployment_order.save
      flash[:success] = "Deployment Order Successfully created"
      redirect_to deployment_orders_path
    else
      render 'new'
    end
  end

  def edit
  end

  def show
    @staff_max = 0
    @deployment_order.unit_deployeds.each do |unit_deployed|
      @staff_max = unit_deployed.unit_deployed_staffs.length if unit_deployed.unit_deployed_staffs.length > @staff_max
    end
    
    respond_to do |format|
      format.html
      format.pdf do
        render pdf: "order",
        template: "deployment_orders/order",
        layout: 'pdf.html'
      end
    end
  end

  def update
    if @deployment_order.update(deployment_order_params)
      flash[:success] = "Deployment Order update"
      redirect_to deployment_order_path(@deployment_order)
    else
      render 'edit'
    end
  end

  def destroy
    @deployment_order.destroy
    flash[:danger] = "Deployment order was Successfully Deleted..."
    redirect_to deployment_orders_path
  end

  private
  def deployment_order_params
    params.require(:deployment_order).permit(:id, :well_name, :date_of_duty, :departure_time, :rig_id, :job_id, :job_ic, :route, :d_site_contact_no, :special_instruction, :unit_deployeds_attributes => [:id, :vehicle_name, :_destroy,  :unit_deployed_staffs_attributes => [:id, :staff_id, :_destroy]], :cement_unit_deployeds_attributes => [:id, :vehicle_name, :quantity, :_destroy], :head_parties_attributes => [:id, :staff_id, :_destroy], :main_parties_attributes => [ :id, :staff_id, :_destroy], :light_vehicals_attributes => [ :id, :vehical_no, :_destroy], :job_incharges_attributes => [:id, :staff_id, :_destroy])
  end

  def set_deployment_order
    @deployment_order = DeploymentOrder.find(params[:id])
  end

  def get_rigs
    @rigs = Rig.all.map{|i| [ i.rig_name , i.id]}
    @jobs = Job.all.map{|i| [ i.name , i.id]}
    @staffs = Staff.all.map{|i| [ "#{i.first_name} #{i.last_name}" , i.id]}
  end
end

app/helpers/deployment_orders_helper.rb
module DeploymentOrdersHelper
end

app/views/deployment_orders/_cement_unit_deployed.html.haml
.row
  .col-md-3
    .mb-3
      = f.label :vehicle_name, {class:'form-label'}
      = f.text_field :vehicle_name, {class:'form-control', placeholder: 'Vehicle name'}
  .col-md-3
    .mb-3
      = f.label :quantity, {class:'form-label'}
      = f.text_field :quantity, {class:'form-control', placeholder: 'Quantity'}
  .col-md-3
    .mb-3.delete
      = link_to '#', class: 'remove_record' do
        %i.far.fa-times-circle
      = f.hidden_field :_destroy

app/views/deployment_orders/_form.html.haml
= render "shared/errors", obj: @deployment_order
%div
  = form_for @deployment_order , :html => {:class => 'form-horizontal', role: 'form'} do |f|
    .row
      .col-md-3
        .mb-3
          = f.label :date_of_duty, "Date of Duty", {class:'form-label'}
          = f.text_field :date_of_duty, {class:'form-control', placeholder: 'Date of Duty', type: 'date'}
      .col-md-3
        .mb-3
          = f.label :rig_id, "Rig Name", {class:'form-label'}
          = f.select :rig_id, @rigs, {}, {class: "form-select"}
      .col-md-3
        .mb-3
          = f.label :well_name, "Well", {class:'form-label'}
          = f.text_field :well_name, {class:'form-control', placeholder: 'Well'}
      .col-md-3
        .mb-3
          - time = @deployment_order.departure_time.present? ? @deployment_order.departure_time : Time.now
          = f.label :departure_time, "Departure time", {class:'form-label datepicker'}
          = f.text_field :departure_time, {class:'form-control', placeholder: 'Date of Duty', type: 'time', value: time.strftime("%k:%M")}
    .row
      .col-md-3
        .mb-3
          = f.label :job_id, "Job", {class:'form-label'}
          = f.select :job_id, @jobs, {}, {class: "form-select"}
    %h4 Unit Deployed
    = f.fields_for :unit_deployeds do |builder|
      = render 'unit_deployed', f: builder
    .unit_deployed
    .row
      .col
        .mb-3
          = link_to_add_row('Add unit deployed', 'unit_deployed', f, :unit_deployeds, class: 'button')
    %h4 Mobile silo Deployed
    = f.fields_for :cement_unit_deployeds do |builder|
      = render 'cement_unit_deployed', f: builder
    .cement_unit
    .row
      .col
        .mb-3
          = link_to_add_row('Add Cement Unit', 'cement_unit', f, :cement_unit_deployeds, class: 'button')
    %h4 Head Party
    .row.head_party
      = f.fields_for :head_parties do |builder|
        = render 'head_party', f: builder
    .row
      .col
        .mb-3
          = link_to_add_row('Add Head party', 'head_party', f, :head_parties, class: 'button')

    %h4 Main Party
    .row.main_party
      = f.fields_for :main_parties do |builder|
        = render 'main_party', f: builder
    .row
      .col
        .mb-3
          = link_to_add_row('Add main party', 'main_party', f, :main_parties, class: 'button')
    %h4 Light vehicles
    .row.light_vehical
      = f.fields_for :light_vehicals do |builder|
        = render 'light_vehical', f: builder
    .row
      .col
        .mb-3
          = link_to_add_row('Add light vehical', 'light_vehical', f, :light_vehicals, class: 'button')
    %h4 Job I/C
    .row.job_incharge
      = f.fields_for :job_incharges do |builder|
        = render 'job_incharge', f: builder
    .row
      .col
        .mb-3
          = link_to_add_row('Add Job I/C', 'job_incharge', f, :job_incharges, class: 'button')
    .row
      -# .col-md-3
      -#   .mb-3
      -#     = f.label :route, "Route", {class:'form-label'}
      -#     = f.text_field :route, {class:'form-control', placeholder: 'Route'}
      -# .col-md-3
      -#   .mb-3
      -#     = f.label :d_site_contact_no, "D/Site Contact no", {class:'form-label'}
      -#     = f.text_field :d_site_contact_no, {class:'form-control', placeholder: 'D/Site Contact no'}
      .col-md-9
        .mb-3
          = f.label :special_instruction, "Special instruction", {class:'form-label datepicker'}
          = f.text_area :special_instruction, {class:'form-control', placeholder: 'Special instruction'}
    = f.submit :class => "btn btn-primary"

:javascript
  $('form').on('change', '.staff_type', function(event) { 
    var select_staff = this;
    $.ajax({
      type: "GET",
      url: "/staffs/staff_list",
      data: {id: $(this).val()},
      cache: false,
      dataType: "json",
      success: function(data){
        let staff_list = $(select_staff).parent().parent().parent().find( ".staff_list" )
        $(staff_list).html("<option value=''>Select</option>");
        
        $.each( data, function( key, value ) {
          $(staff_list).append("<option value='"+value["id"]+"'>"+value["first_name"]+" "+value["last_name"]+"</option>");
        });
        
      }
    });
  });

  $('form').on('click', '.remove_record_unit', function(event) {
    $(this).next('input[type=hidden]').val('1');
    row = $(this).closest('.row').hide();
    row.next().hide();
    row.next().next().hide();
    return event.preventDefault();
  });

  $('form').on('click', '.remove_record', function(event) {
    //$(this).prev('input[type=hidden]').val('1');
    $(this).next('input[type=hidden]').val('1');
    $(this).closest('.row').hide();
    return event.preventDefault();
  });

  $('form').on('click', '.remove_record_hor', function(event) {
    //$(this).prev('input[type=hidden]').val('1');
    $(this).next('input[type=hidden]').val('1');
    $(this).closest('.row').parent().hide();
    return event.preventDefault();
  });

  $('form').on('click', '.unit_add_fields', function(event) {
    var regexp, time;
    time = new Date().getTime();
    regexp = new RegExp($(this).data('id'), 'g');
    //var classname = $(this).data('classname')
    //$('.'+classname).append($(this).data('fields').replace(regexp, time));
    $(this).parent().parent().parent().prev().append($(this).data('fields').replace(regexp, time));
    return event.preventDefault();
  });

  $('form').on('click', '.add_fields', function(event) {
    var regexp, time;
    time = new Date().getTime();
    regexp = new RegExp($(this).data('id'), 'g');
    var classname = $(this).data('classname')
    $('.'+classname).append($(this).data('fields').replace(regexp, time));
    return event.preventDefault();
  });

app/views/deployment_orders/_head_party.html.haml
.col-md-6
  .row
    .col-md-3
      .mb-3
        = label(:post, :staff_type, class:'form-label')
        = select_tag "staff_type_#{rand(2)}", options_for_select([["Officer", 1], ["Staff", 2], ["Contingent", 3]]), {class: "form-select staff_type" , prompt: "Select"}
    .col-md-7
      .mb-3
        = f.label :staff_id, "Staff Name", {class:'form-label'}
        = f.select :staff_id, [], {:prompt => 'Select'}, {class: "form-select staff_list" }
    .col-md-2
      .mb-3.delete
        = link_to '#', class: 'remove_record_hor' do
          %i.far.fa-times-circle
        = f.hidden_field :_destroy

app/views/deployment_orders/_job_incharge.html.haml
.col-md-6
  .row
    .col-md-3
      .mb-3
        = label(:post, :staff_type, class:'form-label')
        = select_tag "staff_type_#{rand(2)}", options_for_select([["Officer", 1], ["Staff", 2], ["Contingent", 3]]), {class: "form-select staff_type" , prompt: "Select"}
    .col-md-7
      .mb-3
        = f.label :staff_id, "Staff Name", {class:'form-label'}
        = f.select :staff_id, [], {:prompt => 'Select'}, {class: "form-select staff_list" }
    .col-md-2
      .mb-3.delete
        = link_to '#', class: 'remove_record_hor' do
          %i.far.fa-times-circle
        = f.hidden_field :_destroy

app/views/deployment_orders/_light_vehical.html.haml
.col-md-4
  .row
    .col-md-10
      .mb-3
        = f.label :vehical_no, "Vehicle no", {class:'form-label'}
        = f.text_field :vehical_no, {class:'form-control', placeholder: 'Vehicle no'}
    .col-md-2
      .mb-3.delete
        = link_to '#', class: 'remove_record_hor' do
          %i.far.fa-times-circle
        = f.hidden_field :_destroy

app/views/deployment_orders/_main_party.html.haml
.col-md-6
  .row
    .col-md-3
      .mb-3
        = label(:post, :staff_type, class:'form-label')
        = select_tag "staff_type_#{rand(2)}", options_for_select([["Officer", 1], ["Staff", 2], ["Contingent", 3]]), {class: "form-select staff_type" , prompt: "Select"}
    .col-md-7
      .mb-3
        = f.label :staff_id, "Staff Name", {class:'form-label'}
        = f.select :staff_id, [], {:prompt => 'Select'}, {class: "form-select staff_list" }
    .col-md-2
      .mb-3.delete
        = link_to '#', class: 'remove_record_hor' do
          %i.far.fa-times-circle
        = f.hidden_field :_destroy

app/views/deployment_orders/_unit_deployed.html.haml
.row
  .col-md-3
    .mb-3
      = f.label :vehicle_name, {class:'form-label'}
      = f.text_field :vehicle_name, {class:'form-control', placeholder: 'Vehicle name'}
  .col-md-2
    .mb-3.delete
      = link_to '#', class: 'remove_record_unit' do
        %i.far.fa-times-circle
      = f.hidden_field :_destroy
.row.staff_deployed
  = f.fields_for :unit_deployed_staffs do |e|
    .col-md-6
      .row
        .col-md-3
          .mb-3
            = label(:post, :staff_type, class:'form-label')
            = select_tag "staff_type_#{rand(2)}", options_for_select([["Officer", 1], ["Staff", 2], ["Contingent", 3]]), {class: "form-select staff_type" , prompt: "Select"}
        .col-md-7
          .mb-3
            = e.label :staff_id, "Staff Name", {class:'form-label'}
            = e.select :staff_id, [], {:prompt => 'Select'}, {class: "form-select staff_list" }
        .col-md-2
          .mb-3.delete
            = link_to '#', class: 'remove_record_hor' do
              %i.far.fa-times-circle
            = e.hidden_field :_destroy

.row
  .col
    .mb-3	
      = link_to_add_row('Add Staff', 'staff_deployed', f, :unit_deployed_staffs, class: 'button')

app/views/deployment_orders/_unit_deployed_staff.html.haml
.col-md-6
  .row
    .col-md-3
      .mb-3
        = label(:post, :staff_type, class:'form-label')
        = select_tag "staff_type_#{rand(2)}", options_for_select([["Officer", 1], ["Staff", 2], ["Contingent", 3]]), {class: "form-select staff_type" , prompt: "Select"}
    .col-md-7
      .mb-3
        = f.label :staff_id, "Staff Name", {class:'form-label'}
        = f.select :staff_id, @staffs, {:prompt => 'Select'}, {class: "form-select staff_list" }
    .col-md-2
      .mb-3.delete
        = link_to '#', class: 'remove_record_hor' do
          %i.far.fa-times-circle
        = f.hidden_field :_destroy

app/views/deployment_orders/edit.html.haml
%h1 Edit Deployment Order
%hr
= render "form"

app/views/deployment_orders/index.html.haml
%h1 List of Deployment Orders
%hr
%table.table.table-hover.table-sm
  %thead
    %tr
      %th{:scope => "col"} Date
      %th{:scope => "col"} Rig
      %th{:scope => "col"} Well
      %th{:scope => "col"} Departure time
      %th{:scope => "col"} Job
      %th.text-end{:scope => "col"} Action
  %tbody
    - @deployment_orders.each do |deployment_order|
      %tr
        %td= deployment_order.date_of_duty.strftime('%d-%m-%Y')
        %td= deployment_order.rig.rig_name
        %td= deployment_order.well_name
        %td= deployment_order.departure_time.strftime("%I:%M")
        %td= deployment_order.job.name
        %td.text-end
          = link_to deployment_order_path(deployment_order) , class: "btn btn-success btn-sm margin_5px" do
            %i.fas.fa-eye
          = link_to deployment_order_path(deployment_order, :format => :pdf) , class: "btn btn-warning btn-sm margin_5px", target: "_blank" do
            %i.fas.fa-file-download
          = link_to edit_deployment_order_path(deployment_order) , class: "btn btn-primary btn-sm margin_5px" do
            %i.far.fa-edit
          = link_to deployment_order_path(deployment_order) , method: :delete ,data: {confirm: "Are you sure"} , class: "btn btn-danger btn-sm margin_5px" do
            %i.far.fa-trash-alt

app/views/deployment_orders/new.html.haml
%h1 New Deployment Order
%hr
= render "form"

app/views/deployment_orders/show.html.haml
%h1 Deployment order
%hr
.row
  .col-md-4
    %label.form-label.fw-bold Date of Duty :
    = @deployment_order.date_of_duty
  .col-md-4
    %label.form-label.fw-bold Rig :
    = @deployment_order.rig.rig_name
  .col-md-4
    %label.form-label.fw-bold Well :
    = @deployment_order.well_name

.row
  .col-md-12
    %label.form-label.fw-bold Job :
    = @deployment_order.job.name
.row
  .col-md-12
    %label.form-label.fw-bold Departure time :
    = @deployment_order.departure_time.strftime("%I:%M %p")
.row
  .col-md-12
    %table.table.table-bordered
      %thead
        %tr
          %th{:scope => "col", :width => '150'} Vehicle
          %th{:scope => "col", :colspan => "#{@staff_max}"} Crew Deployed

      %tbody
        - @deployment_order.unit_deployeds.each do |unit_deployed|
          %tr
            %th{:scope => "row"}= unit_deployed.vehicle_name
            - unit_size = unit_deployed.unit_deployed_staffs.length
            - unit_deployed.unit_deployed_staffs.each do |unit_deployed_staff|
              %td= fullname(unit_deployed_staff.staff) rescue ""
            - for i in unit_size...@staff_max
              %td
        - @deployment_order.cement_unit_deployeds.each do |cement|
          %tr
            %th{:scope => "row"}= cement.vehicle_name
            %td= cement.quantity
            - for i in 1...@staff_max
              %td
.row
  .col-md-12
    %table.table.table-bordered
      %tbody
        %tr
          %th{:scope => "col", :width => '150'} Head Party
          - @deployment_order.head_parties.each do |party|
            %td= fullname(party.staff)
.row
  .col-md-12
    %table.table.table-bordered
      %tbody
        %tr
          %th{:scope => "col", :width => '150'} Main Party
          - @deployment_order.main_parties.each do |party|
            %td= fullname(party.staff)
.row
  .col-md-12
    %table.table.table-bordered
      %tbody
        %tr
          %th{:scope => "col", :width => '150'} Light Vehicle
          - @deployment_order.light_vehicals.each do |vehicle|
            %td= vehicle.vehical_no
.row
  .col-md-12
    %label.form-label.fw-bold Job I/C :
    - staff_name = []
    - @deployment_order.job_incharges.each do |job_incharge|
      -staff_name << fullname(job_incharge.staff)
    = staff_name.join(" , ")
  -# .col-md-12
  -#   %label.form-label.fw-bold Route :
  -#   = @deployment_order.route
  -# .col-md-12
  -#   %label.form-label.fw-bold D/Site Contact no :
  -#   = @deployment_order.d_site_contact_no
  .col-md-12
    %label.form-label.fw-bold Special instruction :
    = @deployment_order.special_instruction
  