config/routes.rb
Rails.application.routes.draw do
  
  resources :jobs
  resources :staffs do 
    get 'staff_list', on: :collection
  end
  resources :deployment_orders
  resources :rigs
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "deployment_orders#index" 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cement_unit_deployed.rb
class CementUnitDeployed < ApplicationRecord
  belongs_to :deployment_order
end

app/models/deployment_order.rb
class DeploymentOrder < ApplicationRecord
	belongs_to :rig
	belongs_to :job
	has_many :unit_deployeds, dependent: :destroy
  accepts_nested_attributes_for :unit_deployeds, allow_destroy: true
  has_many :cement_unit_deployeds, dependent: :destroy
  accepts_nested_attributes_for :cement_unit_deployeds, allow_destroy: true, :reject_if => :reject_cement_unit
  has_many :head_parties, dependent: :destroy
  accepts_nested_attributes_for :head_parties, allow_destroy: true, :reject_if => :reject_party
  has_many :main_parties, dependent: :destroy
  accepts_nested_attributes_for :main_parties, allow_destroy: true, :reject_if => :reject_party
  has_many :light_vehicals, dependent: :destroy
  accepts_nested_attributes_for :light_vehicals, allow_destroy: true, reject_if: :all_blank
  has_many :job_incharges, dependent: :destroy
  accepts_nested_attributes_for :job_incharges, allow_destroy: true, reject_if: :all_blank

  validates :date_of_duty, :well_name, :departure_time, :rig_id, presence: true

  def reject_cement_unit(attributed)
    attributed['vehicle_name'].blank? || attributed['quantity'].blank?
  end

  def reject_party(attributed)
    attributed['staff_id'].blank?
  end
end

app/models/head_party.rb
class HeadParty < ApplicationRecord
  belongs_to :deployment_order
  belongs_to :staff
end

app/models/job.rb
class Job < ApplicationRecord
	has_many :deployment_orders, dependent: :destroy 
end

app/models/job_incharge.rb
class JobIncharge < ApplicationRecord
  belongs_to :deployment_order
  belongs_to :staff
end

app/models/light_vehical.rb
class LightVehical < ApplicationRecord
  belongs_to :deployment_order
end

app/models/main_party.rb
class MainParty < ApplicationRecord
  belongs_to :deployment_order
  belongs_to :staff
end

app/models/rig.rb
class Rig < ApplicationRecord
	has_many :deployment_orders, dependent: :destroy 
  validates :rig_name, presence: true
end

app/models/staff.rb
class Staff < ApplicationRecord
  STAFF_TYPE = {"1" => "Officer", "2" => "Staff", "3" => "Contingent"}
end

app/models/unit_deployed.rb
class UnitDeployed < ApplicationRecord
	belongs_to :deployment_order, optional: true
  has_many :unit_deployed_staffs, dependent: :destroy
  accepts_nested_attributes_for :unit_deployed_staffs, allow_destroy: true, :reject_if => :reject_staffs

  def reject_staffs(attributed)
    attributed['staff_id'].blank?
  end

end

app/models/unit_deployed_staff.rb
class UnitDeployedStaff < ApplicationRecord
  belongs_to :unit_deployed
  belongs_to :staff
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_job, only: [:edit, :show, :update, :destroy]

  def index
    @jobs = Job.all.paginate(page: params[:page], per_page: 10)
  end

  def new
    @job = Job.new
  end

  def create
    @job = Job.new(job_params)
    if @job.save
      flash[:success] = "Job Successfully created"
      redirect_to jobs_path
    else
      render 'new'
    end
  end

  def edit
  end

  def show
  end

  def destroy
    @job.destroy
    flash[:danger] = "Job was Successfully Deleted..."
    redirect_to jobs_path
  end

  private
  def job_params
    params.require(:job).permit(:name)
  end

  def set_job
    @job = Job.find(params[:id])
  end
end

app/controllers/rigs_controller.rb
class RigsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_rig, only: [:edit, :show, :update, :destroy]

  def index
    @rigs = Rig.all.paginate(page: params[:page], per_page: 10)
  end

  def new
    @rig = Rig.new
  end

  def create
    @rig = Rig.new(rig_params)
    if @rig.save
      flash[:success] = "Rig Successfully created"
      redirect_to rigs_path
    else
      render 'new'
    end
  end

  def edit
  end

  def show
  end

  def destroy
    @rig.destroy
    flash[:danger] = "Rig was Successfully Deleted..."
    redirect_to rigs_path
  end

  private
  def rig_params
    params.require(:rig).permit(:rig_name)
  end

  def set_rig
    @rig = Rig.find(params[:id])
  end
end

app/controllers/staffs_controller.rb
class StaffsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_staff, only: [:edit, :show, :update, :destroy]

  def index
    @staffs = Staff.all.paginate(page: params[:page], per_page: 10)
  end

  def new
    @staff = Staff.new
  end

  def create
    @staff = Staff.new(staff_params)
    if @staff.save
      flash[:success] = "Staff Successfully created"
      redirect_to staffs_path
    else
      render 'new'
    end
  end

  def edit
  end

  def show
  end

  def update
    if @staff.update(staff_params)
      flash[:success] = "Staff update"
      redirect_to staffs_path(@staff)
    else
      render 'edit'
    end
  end

  def destroy
    @staff.destroy
    flash[:danger] = "Staff was Successfully Deleted..."
    redirect_to staffs_path
  end

  def staff_list
    @staffs = Staff.where(employee_type: params[:id])
    respond_to do |format|
      format.html
      format.json { render json: @staffs.to_json }
    end
  end

  private
  def staff_params
    params.require(:staff).permit(:first_name, :last_name, :employee_type)
  end

  def set_staff
    @staff = Staff.find(params[:id])
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController  
  before_action :authenticate_user!
	
	def index
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def link_to_add_row(name, class_name, f, association, **args)
    new_object = f.object.send(association).klass.new
    id = new_object.object_id
    fields = f.fields_for(association, new_object, child_index: id) do |builder|
      render(association.to_s.singularize, f: builder)
    end
    if class_name == "staff_deployed"
      link_to(name, 'javascript:void(0);', class: "unit_add_fields " + args[:class], data: {id: id, classname: class_name, fields: fields.gsub("\n", "")})
    else
      link_to(name, 'javascript:void(0);', class: "add_fields " + args[:class], data: {id: id, classname: class_name, fields: fields.gsub("\n", "")})
    end
  end

  def will_paginate(collection_or_options = nil, options = {})
    if collection_or_options.is_a? Hash
      options, collection_or_options = collection_or_options, nil
    end
    unless options[:renderer]
      options = options.merge :renderer => BootstrapRenderer
    end
    super *[collection_or_options, options].compact
  end

  class BootstrapRenderer < WillPaginate::ActionView::LinkRenderer
    protected
    def html_container(html)
      tag :nav, tag(:ul, html, class: "pagination pagination-sm"), container_attributes
    end

    def page_number(page)
      tag :li, link(page, page, rel: rel_value(page), class: 'page-link'),
        class: (page == current_page ? 'page-item active': 'page-item')
    end

    def previous_or_next_page(page, text, classname)
      tag :li, link(text, page || '#', class: 'page-link'),
        class: ['page-item', classname, ('disabled' unless page)].join(' ')
    end
  end
end

app/helpers/deployment_orders_helper.rb
module DeploymentOrdersHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/rigs_helper.rb
module RigsHelper
end

app/helpers/staffs_helper.rb
module StaffsHelper
  def fullname(staff)
		return "#{staff.first_name} #{staff.last_name}"
	end
end

app/views/jobs/_form.html.haml
= render "shared/errors", obj: @job
= form_for @job , :html => {:class => 'form-horizontal', role: 'form'} do |f|
  .form-row
    .mb-3
      = f.label :name, "Job", {class:'form-label'}
      = f.text_field :name, {class:'form-control', placeholder: 'Job'}
    = f.submit :class => "btn btn-primary"

app/views/jobs/index.html.haml
%h1 List of Jobs
%hr
%table.table.table-hover.table-sm
  %thead
    %tr
      %th{:scope => "col"} Name
      %th.text-end{:scope => "col"} Action
  %tbody
    - @jobs.each do |job|
      %tr
        %td= job.name 
        %td.text-end
          = link_to job_path(job) , class: "btn btn-success btn-sm margin_5px" do
            %i.fas.fa-eye
          = link_to edit_job_path(job) , class: "btn btn-primary btn-sm margin_5px" do
            %i.far.fa-edit
          = link_to job_path(job) , method: :delete ,data: {confirm: "Are you sure"} , class: "btn btn-danger btn-sm margin_5px" do
            %i.far.fa-trash-alt
= will_paginate @jobs

app/views/jobs/new.html.haml
%h1 New Job
%hr
= render "form"

app/views/rigs/_form.html.haml
= render "shared/errors", obj: @rig
= form_for @rig , :html => {:class => 'form-horizontal', role: 'form'} do |f|
  .form-row
    .mb-3
      = f.label :rig_name, "Rig", {class:'form-label'}
      = f.text_field :rig_name, {class:'form-control', placeholder: 'Rig'}
    = f.submit :class => "btn btn-primary"

app/views/rigs/index.html.haml
%h1 List of Rigs
%hr
%table.table.table-hover.table-sm
	%thead
		%tr
			%th{:scope => "col"} Rig
			%th.text-end{:scope => "col"} Action
	%tbody
		- @rigs.each do |rig|
			%tr
				%td= rig.rig_name 
				%td.text-end
					= link_to rig_path(rig) , class: "btn btn-success btn-sm margin_5px" do
						%i.fas.fa-eye
					= link_to edit_rig_path(rig) , class: "btn btn-primary btn-sm margin_5px" do
						%i.far.fa-edit
					= link_to rig_path(rig) , method: :delete ,data: {confirm: "Are you sure"} , class: "btn btn-danger btn-sm margin_5px" do
						%i.far.fa-trash-alt
= will_paginate @rigs

app/views/rigs/new.html.haml
%h1 New Rig
%hr
= render "form"

app/views/staffs/_form.html.haml
= render "shared/errors", obj: @staff
= form_for @staff , :html => {:class => 'form-horizontal', role: 'form'} do |f|
  .form-row
    .row
      .col-md-4
        .mb-3
          = f.label :first_name, {class:'form-label'}
          = f.text_field :first_name, {class:'form-control', placeholder: 'First name'}
      .col-md-4
        .mb-3
          = f.label :last_name, {class:'form-label'}
          = f.text_field :last_name, {class:'form-control', placeholder: 'Last name'}
      .col-md-4
        .mb-3
          = f.label :employee_type, {class:'form-label'}
          = f.select :employee_type, [["Officer", 1], ["Staff", 2], ["Contingent", 3]], {:prompt => 'Select'}, {class: "form-select" }
    = f.submit :class => "btn btn-primary"

app/views/staffs/edit.html.haml
%h1 Edit Staff
%hr
= render "form"

app/views/staffs/index.html.haml
%h1 List of Staffs
%hr
%table.table.table-hover.table-sm
  %thead
    %tr
      %th{:scope => "col"} Name
      %th.text-end{:scope => "col"} Action
  %tbody
    - @staffs.each do |staff|
      %tr
        
        %td= fullname(staff) 
        %td.text-end
          = link_to staff_path(staff) , class: "btn btn-success btn-sm margin_5px" do
            %i.fas.fa-eye
          = link_to edit_staff_path(staff) , class: "btn btn-primary btn-sm margin_5px" do
            %i.far.fa-edit
          = link_to staff_path(staff) , method: :delete ,data: {confirm: "Are you sure"} , class: "btn btn-danger btn-sm margin_5px" do
            %i.far.fa-trash-alt
= will_paginate @staffs

app/views/staffs/new.html.haml
%h1 New Staff
%hr
= render "form"

app/views/staffs/show.html.haml
%h1 Staffs
%hr
.row
  .col-md-4
    %label.form-label.fw-bold Name :
    = fullname(@staff)
  .col-md-4
    %label.form-label.fw-bold Employee type :
    = Staff::STAFF_TYPE[@staff.employee_type.to_s]