config/routes.rb
Rails.application.routes.draw do
  
  resources :jobs
  resources :staffs do 
    get 'staff_list', on: :collection
  end
  resources :deployment_orders
  resources :rigs
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "deployment_orders#index" 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cement_unit_deployed.rb
class CementUnitDeployed < ApplicationRecord
  belongs_to :deployment_order
end

app/models/deployment_order.rb
class DeploymentOrder < ApplicationRecord
	belongs_to :rig
	belongs_to :job
	has_many :unit_deployeds, dependent: :destroy
  accepts_nested_attributes_for :unit_deployeds, allow_destroy: true
  has_many :cement_unit_deployeds, dependent: :destroy
  accepts_nested_attributes_for :cement_unit_deployeds, allow_destroy: true, :reject_if => :reject_cement_unit
  has_many :head_parties, dependent: :destroy
  accepts_nested_attributes_for :head_parties, allow_destroy: true, :reject_if => :reject_party
  has_many :main_parties, dependent: :destroy
  accepts_nested_attributes_for :main_parties, allow_destroy: true, :reject_if => :reject_party
  has_many :light_vehicals, dependent: :destroy
  accepts_nested_attributes_for :light_vehicals, allow_destroy: true, reject_if: :all_blank
  has_many :job_incharges, dependent: :destroy
  accepts_nested_attributes_for :job_incharges, allow_destroy: true, reject_if: :all_blank

  validates :date_of_duty, :well_name, :departure_time, :rig_id, presence: true

  def reject_cement_unit(attributed)
    attributed['vehicle_name'].blank? || attributed['quantity'].blank?
  end

  def reject_party(attributed)
    attributed['staff_id'].blank?
  end
end

app/models/head_party.rb
class HeadParty < ApplicationRecord
  belongs_to :deployment_order
  belongs_to :staff
end

app/models/job.rb
class Job < ApplicationRecord
	has_many :deployment_orders, dependent: :destroy 
end

app/models/job_incharge.rb
class JobIncharge < ApplicationRecord
  belongs_to :deployment_order
  belongs_to :staff
end

app/models/light_vehical.rb
class LightVehical < ApplicationRecord
  belongs_to :deployment_order
end

app/models/main_party.rb
class MainParty < ApplicationRecord
  belongs_to :deployment_order
  belongs_to :staff
end

app/models/rig.rb
class Rig < ApplicationRecord
	has_many :deployment_orders, dependent: :destroy 
  validates :rig_name, presence: true
end

app/models/staff.rb
class Staff < ApplicationRecord
  STAFF_TYPE = {"1" => "Officer", "2" => "Staff", "3" => "Contingent"}
end

app/models/unit_deployed.rb
class UnitDeployed < ApplicationRecord
	belongs_to :deployment_order, optional: true
  has_many :unit_deployed_staffs, dependent: :destroy
  accepts_nested_attributes_for :unit_deployed_staffs, allow_destroy: true, :reject_if => :reject_staffs

  def reject_staffs(attributed)
    attributed['staff_id'].blank?
  end

end

app/models/unit_deployed_staff.rb
class UnitDeployedStaff < ApplicationRecord
  belongs_to :unit_deployed
  belongs_to :staff
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_job, only: [:edit, :show, :update, :destroy]

  def index
    @jobs = Job.all.paginate(page: params[:page], per_page: 10)
  end

  def new
    @job = Job.new
  end

  def create
    @job = Job.new(job_params)
    if @job.save
      flash[:success] = "Job Successfully created"
      redirect_to jobs_path
    else
      render 'new'
    end
  end

  def edit
  end

  def show
  end

  def destroy
    @job.destroy
    flash[:danger] = "Job was Successfully Deleted..."
    redirect_to jobs_path
  end

  private
  def job_params
    params.require(:job).permit(:name)
  end

  def set_job
    @job = Job.find(params[:id])
  end
end

app/controllers/rigs_controller.rb
class RigsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_rig, only: [:edit, :show, :update, :destroy]

  def index
    @rigs = Rig.all.paginate(page: params[:page], per_page: 10)
  end

  def new
    @rig = Rig.new
  end

  def create
    @rig = Rig.new(rig_params)
    if @rig.save
      flash[:success] = "Rig Successfully created"
      redirect_to rigs_path
    else
      render 'new'
    end
  end

  def edit
  end

  def show
  end

  def destroy
    @rig.destroy
    flash[:danger] = "Rig was Successfully Deleted..."
    redirect_to rigs_path
  end

  private
  def rig_params
    params.require(:rig).permit(:rig_name)
  end

  def set_rig
    @rig = Rig.find(params[:id])
  end
end

app/controllers/staffs_controller.rb
class StaffsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_staff, only: [:edit, :show, :update, :destroy]

  def index
    @staffs = Staff.all.paginate(page: params[:page], per_page: 10)
  end

  def new
    @staff = Staff.new
  end

  def create
    @staff = Staff.new(staff_params)
    if @staff.save
      flash[:success] = "Staff Successfully created"
      redirect_to staffs_path
    else
      render 'new'
    end
  end

  def edit
  end

  def show
  end

  def update
    if @staff.update(staff_params)
      flash[:success] = "Staff update"
      redirect_to staffs_path(@staff)
    else
      render 'edit'
    end
  end

  def destroy
    @staff.destroy
    flash[:danger] = "Staff was Successfully Deleted..."
    redirect_to staffs_path
  end

  def staff_list
    @staffs = Staff.where(employee_type: params[:id])
    respond_to do |format|
      format.html
      format.json { render json: @staffs.to_json }
    end
  end

  private
  def staff_params
    params.require(:staff).permit(:first_name, :last_name, :employee_type)
  end

  def set_staff
    @staff = Staff.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def link_to_add_row(name, class_name, f, association, **args)
    new_object = f.object.send(association).klass.new
    id = new_object.object_id
    fields = f.fields_for(association, new_object, child_index: id) do |builder|
      render(association.to_s.singularize, f: builder)
    end
    if class_name == "staff_deployed"
      link_to(name, 'javascript:void(0);', class: "unit_add_fields " + args[:class], data: {id: id, classname: class_name, fields: fields.gsub("\n", "")})
    else
      link_to(name, 'javascript:void(0);', class: "add_fields " + args[:class], data: {id: id, classname: class_name, fields: fields.gsub("\n", "")})
    end
  end

  def will_paginate(collection_or_options = nil, options = {})
    if collection_or_options.is_a? Hash
      options, collection_or_options = collection_or_options, nil
    end
    unless options[:renderer]
      options = options.merge :renderer => BootstrapRenderer
    end
    super *[collection_or_options, options].compact
  end

  class BootstrapRenderer < WillPaginate::ActionView::LinkRenderer
    protected
    def html_container(html)
      tag :nav, tag(:ul, html, class: "pagination pagination-sm"), container_attributes
    end

    def page_number(page)
      tag :li, link(page, page, rel: rel_value(page), class: 'page-link'),
        class: (page == current_page ? 'page-item active': 'page-item')
    end

    def previous_or_next_page(page, text, classname)
      tag :li, link(text, page || '#', class: 'page-link'),
        class: ['page-item', classname, ('disabled' unless page)].join(' ')
    end
  end
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/rigs_helper.rb
module RigsHelper
end

app/helpers/staffs_helper.rb
module StaffsHelper
  def fullname(staff)
		return "#{staff.first_name} #{staff.last_name}"
	end
end

app/views/layouts/_flash.html.haml
.container
  .row
    .col-sm-12
      - flash.each do |name,msg|
        %div{class: "alert alert-#{"#{name}"}"}
          -# %button.close{"aria-label" => "Close", "data-dismiss" => "alert", type: "button"}
          -#   %span{"aria-hidden" => "true"} ×
          = content_tag :div, msg, id: "flash_#{name}" if msg.is_a?(String)

app/views/layouts/_navigation.html.haml
%header.p-3.mb-3.border-bottom
  .container
    .d-flex.flex-wrap.align-items-center.justify-content-center.justify-content-lg-start
      %a.d-flex.align-items-center.mb-2.mb-lg-0.text-dark.text-decoration-none{:href => "/"}
        = image_tag image_url('logo.png'), size: "50"
      - if current_user
        %ul.nav.col-12.col-lg-auto.me-lg-auto.mb-2.justify-content-center.mb-md-0
          %li.nav-item.dropdown
            %a#navbarDropdown.nav-link.dropdown-toggle{"aria-expanded" => "false", "data-bs-toggle" => "dropdown", :href => "#", :role => "button"}
              Deploymnet Order
            %ul.dropdown-menu{"aria-labelledby" => "navbarDropdown"}
              %li
                = link_to('New Deployment', new_deployment_order_path, class:"dropdown-item")
              %li
                = link_to('List Deployment', deployment_orders_path, class:"dropdown-item")
          %li.nav-item.dropdown
            %a#navbarDropdown.nav-link.dropdown-toggle{"aria-expanded" => "false", "data-bs-toggle" => "dropdown", :href => "#", :role => "button"}
              Rig
            %ul.dropdown-menu{"aria-labelledby" => "navbarDropdown"}
              %li
                = link_to('New Rig', new_rig_path, class:"dropdown-item")
              %li
                = link_to('List Rig', rigs_path, class:"dropdown-item")
          %li.nav-item.dropdown
            %a#navbarDropdown.nav-link.dropdown-toggle{"aria-expanded" => "false", "data-bs-toggle" => "dropdown", :href => "#", :role => "button"}
              Job
            %ul.dropdown-menu{"aria-labelledby" => "navbarDropdown"}
              %li
                = link_to('New Job', new_job_path, class:"dropdown-item")
              %li
                = link_to('List Job', jobs_path, class:"dropdown-item")
          %li.nav-item.dropdown
            %a#navbarDropdown.nav-link.dropdown-toggle{"aria-expanded" => "false", "data-bs-toggle" => "dropdown", :href => "#", :role => "button"}
              Staff
            %ul.dropdown-menu{"aria-labelledby" => "navbarDropdown"}
              %li
                = link_to('New Staff', new_staff_path, class:"dropdown-item")
              %li
                = link_to('List Staff', staffs_path, class:"dropdown-item")
                
        .dropdown.text-end
          %a#dropdownUser1.d-block.link-dark.text-decoration-none.dropdown-toggle{"aria-expanded" => "false", "data-bs-toggle" => "dropdown", :href => "#"}
            %img.rounded-circle{:alt => "mdo", :height => "32", :src => "https://github.com/mdo.png", :width => "32"}/
          %ul.dropdown-menu.text-small{"aria-labelledby" => "dropdownUser1", :style => ""}
            -# %li
            -#   %a.dropdown-item{:href => "#"} Profile
            %li
              %hr.dropdown-divider/
            %li
              = link_to('Sign out', destroy_user_session_path, method: :delete, class:"dropdown-item")

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Cementing app
    %meta{:content => "width=device-width,initial-scale=1", :name => "viewport"}/
    = csrf_meta_tags
    = csp_meta_tag
    / Warning !! ensure that "stylesheet_pack_tag" is used, line below
    = stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    %script{:crossorigin => "anonymous", :integrity => "sha512-894YE6QWD5I59HgZOGReFYm4dnWc1Qt5NtvYSaNcOP+u1T9qYdvdihz0PPSiiqn/+/3e7Jo4EaG7TubfWGUrMQ==", :referrerpolicy => "no-referrer", :src => "https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js"}
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = render "layouts/navigation"
    = render "layouts/flash"
    .container.margin_100px
      = yield
    %footer.footer.mt-auto.py-3.bg-light
      .container
        %span.text-muted Cementing app

app/views/layouts/login_layout.html.haml
!!!
%html
  %head
    %title Myapp
    %meta{:content => "width=device-width,initial-scale=1", :name => "viewport"}/
    = csrf_meta_tags
    = csp_meta_tag
    / Warning !! ensure that "stylesheet_pack_tag" is used, line below
    = stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    =# render "layouts/flash"
    .form-signin
      .text-center.mb-4
        %svg.bi.me-2{"aria-label" => "Bootstrap", :height => "32", :role => "img", :width => "40"}
          %use{"xlink:href" => "#bootstrap"}
            %symbol#bootstrap{:viewbox => "0 0 118 94"}
              %title Bootstrap
              %path{"clip-rule" => "evenodd", :d => "M24.509 0c-6.733 0-11.715 5.893-11.492 12.284.214 6.14-.064 14.092-2.066 20.577C8.943 39.365 5.547 43.485 0 44.014v5.972c5.547.529 8.943 4.649 10.951 11.153 2.002 6.485 2.28 14.437 2.066 20.577C12.794 88.106 17.776 94 24.51 94H93.5c6.733 0 11.714-5.893 11.491-12.284-.214-6.14.064-14.092 2.066-20.577 2.009-6.504 5.396-10.624 10.943-11.153v-5.972c-5.547-.529-8.934-4.649-10.943-11.153-2.002-6.484-2.28-14.437-2.066-20.577C105.214 5.894 100.233 0 93.5 0H24.508zM80 57.863C80 66.663 73.436 72 62.543 72H44a2 2 0 01-2-2V24a2 2 0 012-2h18.437c9.083 0 15.044 4.92 15.044 12.474 0 5.302-4.01 10.049-9.119 10.88v.277C75.317 46.394 80 51.21 80 57.863zM60.521 28.34H49.948v14.934h8.905c6.884 0 10.68-2.772 10.68-7.727 0-4.643-3.264-7.207-9.012-7.207zM49.948 49.2v16.458H60.91c7.167 0 10.964-2.876 10.964-8.281 0-5.406-3.903-8.178-11.425-8.178H49.948z", "fill-rule" => "evenodd"}svg", :width => "72"}/
        = yield
    :css
      body {
        height: 100%;
      }
      
      body {
        display: -ms-flexbox;
        display: -webkit-box;
        display: flex;
        -ms-flex-align: center;
        -ms-flex-pack: center;
        -webkit-box-align: center;
        align-items: center;
        -webkit-box-pack: center;
        justify-content: center;
        padding-top: 40px;
        padding-bottom: 40px;
        background-color: #f5f5f5;
      }
      .form-control {
        display: block;
        width: 100%;
        padding: .375rem .75rem;
        font-size: 1rem;
        line-height: 1.5;
        color: #495057;
        background-color: #fff;
        background-clip: padding-box;
        border: 1px solid #ced4da;
        border-radius: .25rem;
        transition: border-color .15s ease-in-out,box-shadow .15s ease-in-out;
      }
      .form-signin {
        width: 100%;
        max-width: 420px;
        padding: 15px;
        margin: 0 auto;
      }
      
      .form-label-group {
        position: relative;
        margin-bottom: 1rem;
      }
      
      .form-label-group > input,
      .form-label-group > label {
        /*padding: var(--input-padding-y) var(--input-padding-x);*/
        padding: 10px;
        text-align: left;
      }
      
      .form-label-group > label {
        position: absolute;
        top: 0;
        left: 0;
        display: block;
        width: 100%;
        margin-bottom: 0; /* Override default `<label>` margin */
        line-height: 1.5;
        color: #495057;
        border: 1px solid transparent;
        border-radius: .25rem;
        transition: all .1s ease-in-out;
      }
      
      .form-label-group input::-webkit-input-placeholder {
        color: transparent;
      }
      
      .form-label-group input:-ms-input-placeholder {
        color: transparent;
      }
      
      .form-label-group input::-ms-input-placeholder {
        color: transparent;
      }
      
      .form-label-group input::-moz-placeholder {
        color: transparent;
      }
      
      .form-label-group input::placeholder {
        color: transparent;
      }
      
      .form-label-group input:not(:placeholder-shown) {
        /*padding-top: calc(var(--input-padding-y) + var(--input-padding-y) * (2 / 3));
        padding-bottom: calc(var(--input-padding-y) / 3);*/
      }
      
      .form-label-group input:not(:placeholder-shown) ~ label {
        padding-top: calc(var(--input-padding-y) / 3);
        padding-bottom: calc(var(--input-padding-y) / 3);
        font-size: 12px;
        color: #777;
        text-align: left;
      }
      .btn-block {
        display: block;
        width: 100%;
      }

app/views/layouts/pdf.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PDF</title>
    <%#= wicked_pdf_stylesheet_link_tag "application"%>
    <%#= wicked_pdf_javascript_include_tag "application" %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@100;300;400;500&display=swap" rel="stylesheet">  
    <%#= stylesheet_pack_tag "application"%>
    <%#= javascript_pack_tag "application" %>
  </head>
  <body class="pdf">
    <div class='container'>
      <%= yield %>
    </div>
  </body>
  <style>
    body{font-family: 'Roboto'}
    h1{font-weight: 500;font-size: 2.5rem;}
    h2.ongc{font-weight: 500;font-size: 1.7rem;}
    table tr th, table tr td {
      text-align: left;
    }
    th.crew{text-align: center;}
    table.ongc_header td:last-child{padding: 0.10rem 0.25rem;}
    table.ongc_header td:last-child{ font-size: 15px;}
    td.dob{ border-style: none; border-color: none;}
  </style>
</html>

app/views/shared/_errors.html.haml
- if obj.errors.any?
  .row
    .col-sm-8.offset-sm-2
      .card.border-danger
        .card-header
          %h2.card-title
            = pluralize(obj.errors.count , "error")
            List of Errors
        .card-body.text-danger
          %ul
            - obj.errors.full_messages.each do |error|
              %li= error